# Generated by Django 5.2.5 on 2025-09-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
